shamefullyHoist: true

catalog:
  "@antfu/eslint-config": ^4.13.0
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.0
  eslint: ^9.26.0
  tsdown: ^0.11.9
  vitest: ^3.1.3

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
